export const SET_USER = 'SET_USER'
export const REMOVE_USER = 'REMOVE_USER'
export const LOADING_SHOW = 'LOADING_SHOW'
export const LOADING_HIDE = 'LOADING_HIDE'
export const SET_ARTICLELIST = 'SET_ARTICLELIST'
export const SET_CATEGORY = 'SET_CATEGORY'

// 设置文章表单
export const SET_ARTICLE_FORM = 'SET_ARTICLE_FORM'

export default {
    SET_USER,
    REMOVE_USER,
    LOADING_SHOW,
    LOADING_HIDE,
    SET_ARTICLELIST,
    SET_CATEGORY,
    SET_ARTICLE_FORM
}

